version: "3.8"

services:

  postgres:
    image: postgres:16
    container_name: postgresDB
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sunny@1012
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: kartheek018/activity-api:latest
    container_name: activity-api
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  postgres_data: