spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Sunny@1012
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true