spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Sunny@1012
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

WEB_PORT: 8083